name: Replace Paths
on:
  push:
      branches:
        - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'src="static/'
          replace: 'src="./static/'
          include: "index.html"
